# Chapter 2: Variables and basic data

## 2.7: Introducing NUmpy Arrays.
a few important features for Numpy is listed:
* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

In [1]:
import numpy as np

**TRY IT!** Create the following arrays:

$x = \begin{pmatrix} 
1 & 4 & 3 \\
\end{pmatrix}$

$y = \begin{pmatrix} 
1 & 4 & 3 \\
9 & 2 & 7 \\
\end{pmatrix}$

In [2]:
x = np.array([1, 4, 3])
x
y = np.array([[1, 4, 3], [9, 2, 7]])
y

array([[1, 4, 3],
       [9, 2, 7]])

**NOTE!** A 2-D array could use a nested lists to represent, with the inner list represent each row. 

- If you would like to get the size or length of an array.
-  The array *shape* attribute is called on an array M and returns a 2 × 3 array  
- The **first element** is the **number of rows** in the matrix M
- The **second element** is the **number of columns** in M.

In [3]:
y.shape

(2, 3)

In [4]:
y.size

6

For generating arrays that are in order and evenly spaced, it is useful to use the *arange* function in Numpy.

**TRY IT!** Create an array *z* from 1 to 2000 with an increment 1. 

In [5]:
z = np.arange(1, 2000, 1)
z

array([   1,    2,    3, ..., 1997, 1998, 1999])

Using the *np.arange*

**TRY IT!** Generate an array with [0.5, 1, 1.5, 2, 2.5]. 

In [6]:
np.arange(0.5, 3, 0.5)

array([0.5, 1. , 1.5, 2. , 2.5])

If we want a guarantee start and end point for an array but still evenly spaced elements.
- We can use ***np.linspace***

**TRY IT!** Use *linspace* to generate an array starting at 3, ending at 9, and containing 10 elements.

In [7]:
np.linspace(3, 9, 10)

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

Getting access to the 1D numpy array is similar to what we described for lists or tuples, it has an index to indicate the location. For example:

In [8]:
# get the 2nd element of x
x[1]
# get all the element after the 2nd element of x
x[1:]
# get the last element of x
x[-1]

3

For 2D arrys:
- To get access to the data in a 2D array M, we need to use **M[r,c]**
- Where r is row and c is column
The r and c could be single number, a list and so on. If you only think about the row index or the column index, than it is similar to the 1D array. Let's use the $y = \begin{pmatrix} 
1 & 4 & 3 \\
9 & 2 & 7 \\
\end{pmatrix}$ as an example. 

**TRY IT!** Get the element at first row and 2nd column of array *y*.

In [9]:
y[0,1]

4

**TRY IT!** Get the first row of array *y*. 

In [10]:
y[0, :]

array([1, 4, 3])

**TRY IT!** Get the first and third column of array *y*.

In [12]:
y[:, [0, 2]]

array([[1, 3],
       [9, 7]])

Some predefined arrays that are really useful. For example, the ***np.zeros***, ***np.ones***, and ***np.empty***

**TRY IT!** Generate a 3 by 5 array with all the as 0. 

In [ ]:
np.zeros((3, 5))

**TRY IT!** Generate a 5 by 3 array with all the element as 1.

In [ ]:
np.ones((5, 3))

**NOTE!** The shape of the array is defined in a tuple with row as the first item, and column as the second. If you only need a 1D array, then it could be only one number as the input: ***np.ones(5)***.

**TRY IT!** Generate a 1D empty array with 3 elements.

In [13]:
np.empty(3)

array([4.24399158e-314, 4.23762559e-311, 4.24186959e-311])

**NOTE!** The empty array is not really empty, it is filled with random very small numbers. 

- You can reassign a value of an array by using array indecing and the assignment operator.
- You can reassign multiple elements to a single number using array indexing on the left side.
- You can also reassign multiple elements of an array as long as both the number of elements being assigned and the number of elements assigned is the same. 
- You can create an array using array indexing.

**TRY IT!** Let a = [1, 2, 3, 4, 5, 6]. Reassign the fourth element of A to 7. Reassign the first, second, and thrid elements to 1. Reassign the second, third, and fourth elements to 9, 8, and 7. 

In [14]:
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [15]:
a[3] = 7
a

array([1, 2, 3, 7, 5, 6])

In [16]:
a[:3] = 1
a

array([1, 1, 1, 7, 5, 6])

In [17]:
a[:3] = 1
a

array([1, 1, 1, 7, 5, 6])

**TRY IT!** Create a zero array b with shape 2 by 2, and set $b = \begin{pmatrix} 
1 & 2 \\
3 & 4  \\
\end{pmatrix}$ using array indexing. 

In [18]:
b = np.zeros((2, 2))
b[0, 0] = 1
b[0, 1] = 2
b[1, 0] = 3
b[1, 1] = 4
b

array([[1., 2.],
       [3., 4.]])

**WARNING!** Although you can create an array from scratch using indexing, we do not advise it. It can confuse you and errors will be harder to find in your code later. For example, b[1, 1] = 1 will give the result $b = \begin{pmatrix} 
0 & 0 \\
0 & 1  \\
\end{pmatrix}$, which is strange because b[0, 0], b[0, 1], and b[1, 0] were never specified.

*b + c*, adds a to every element of b

*b − c*, subtracts c from every element of b

*b * c*, multiplies every element of b by c

*b / c*, divides every element of b by c

**TRY IT!** Let $b = \begin{pmatrix} 
1 & 2 \\
3 & 4  \\
\end{pmatrix}$. Add and substract 2 from b. Multiply and divide b by 2. Square every element of b. Let c be a scalar. On your own, verify the reflexivity of scalar addition and multiplication: b + c = c + b and cb = bc.

In [19]:
b + 2

array([[3., 4.],
       [5., 6.]])

In [20]:
b - 2

array([[-1.,  0.],
       [ 1.,  2.]])

In [21]:
2 * b

array([[2., 4.],
       [6., 8.]])

In [22]:
b / 2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [23]:
b**2

array([[ 1.,  4.],
       [ 9., 16.]])

#### Describing Operations bewtween Two matrices
Describing operations between two matrices is more complicated. 
- Let b and d be two matrices of the same size. 
- b − d takes every element of b and subtracts the corresponding element of d. 
- Similarly, b + d adds every element of d to the corresponding element of b.

**TRY IT!** Let $b = \begin{pmatrix} 
1 & 2 \\
3 & 4  \\
\end{pmatrix}$ and $d = \begin{pmatrix} 
3 & 4 \\
5 & 6  \\
\end{pmatrix}$. Compute b + d and b - d. 

In [24]:
b = np.array([[1, 2], [3, 4]])
d = np.array([[3, 4], [5, 6]])

In [25]:
b + d

array([[ 4,  6],
       [ 8, 10]])

In [26]:
b - d

array([[-2, -2],
       [-2, -2]])

There are **two different kinds** of matrix multiplication (and division). 

- There is **element-by-element matrix multiplication** and **standard matrix multiplication**. 

- For this section, we will **only show** how **element-by-element matrix multiplication and division** work.
- For matrices b and d of the same size, b * d takes every element of b and multiplies it by the corresponding element of d. The same is true for / and **.

**TRY IT!** Compute b * d, b / d, and b**d. 

In [28]:
b * d

array([[ 3,  8],
       [15, 24]])

In [29]:
b / d

array([[0.33333333, 0.5       ],
       [0.6       , 0.66666667]])

In [30]:
b**d

array([[   1,   16],
       [ 243, 4096]])

#### Transpose
The transpose of an array, b, is an array, d, where b[i, j] = d[j, i]. 
- In other words, the transpose **switches the rows and the columns** of b. You can transpose an array in Python using the array method *T*. 

**TRY IT!** Compute the transpose of array b. 

In [31]:
b.T

array([[1, 3],
       [2, 4]])

#### Arithmetic Functions
Numpy has many arithmetic functions, such as sin, cos, etc., can take arrays as input arguments. 
- The output is the function evaluated for every element of the input array. 
- A function that takes an array as input and performs the function on it is said to be **vectorized**. 

**TRY IT!** Compute *np.sqrt* for x = [1, 4, 9, 16]. 

In [32]:
x = [1, 4, 9, 16]
np.sqrt(x)

array([1., 2., 3., 4.])

#### Logical Operations
Logical operations are only defined between a scalar and an array and between two arrays of the same size. 
- Between a scalar and an array, the logical operation is conducted between the scalar and each element of the array. 
- Between two arrays, the **logical operation is conducted element-by-element**.

**TRY IT!** Check which elements of the array x = [1, 2, 4, 5, 9, 3] are larger than 3. Check which elements in x are larger than the corresponding element in y = [0, 2, 3, 1, 2, 3].

In [33]:
x = np.array([1, 2, 4, 5, 9, 3])
y = np.array([0, 2, 3, 1, 2, 3])

In [34]:
x > 3

array([False, False,  True,  True,  True, False])

In [35]:
x > y

array([ True, False,  True,  True,  True, False])

Python can index elements of an array that satisfy a logical expression. 

**TRY IT!** Let x be the same array as in the previous example. Create a variable y that contains all the elements of x that are strictly bigger than 3. Assign all the values of x that are bigger than 3, the value 0. 

In [36]:
y = x[x > 3]
y

array([4, 5, 9])

In [37]:
x[x > 3] = 0
x

array([1, 2, 0, 0, 0, 3])